# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hughey-lab-theme"
license = "MIT"
licenselink = "https://gitlab.com/hugheylab/hughey-lab-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://gitlab.com/hugheylab/hughey-lab-theme"
tags = []
features = []
min_version = "0.26"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
